
server:
 port: 8082
server.servlet.contextPath: /product-service
postgres:
 properties:
  ddlAuto: create-drop
  dialect: org.hibernate.dialect.PostgreSQLDialect
 datasource:
  platform: postgres
  url: jdbc:postgresql://product.c5y0y2gcwxmw.eu-north-1.rds.amazonaws.com/postgres
  username: postgres
  password: India@123
  driverClassName: org.postgresql.Driver

spring: 
 jpa:
  properties:
   hibernate:
    jdbc:
     lob:
      non_contextual_creation: true
 application:
  name: product-service
eureka:
 client:
  register-with-eureka: false
  service-url:
   defaultZone: http://localhost:8761/eureka
