
server:
 port: 8092
server.servlet.contextPath: /product-service
logging.level.root: TRACE
postgres:
 properties:
  ddlAuto: create-drop
  dialect: org.hibernate.dialect.PostgreSQLDialect
 datasource:
  platform: postgres
  url: jdbc:postgresql://localhost:5432/product
  username: postgres
  password: India@123
  driverClassName: org.postgresql.Driver

spring: 
 jpa:
  properties:
   hibernate:
    jdbc:
     lob:
      non_contextual_creation: true
 application:
  name: product-service
eureka:
 client:
  register-with-eureka: true
  service-url:
   defaultZone: http://localhost:8761/eureka